tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "apr-util"
brew "readline", link: true
brew "python@3.9"
brew "glib"
brew "ghq"
brew "git"
brew "git-secrets"
brew "go"
brew "grep"
brew "jq"
brew "libsass"
brew "nvm"
brew "mas"
brew "peco"
brew "php"
brew "phplint"
brew "pyenv"
brew "telnet"
brew "tfenv"
brew "tree"
brew "wget"
brew "zsh"

# cask "appcleaner"
# cask "bettertouchtool"
# cask "docker"
# cask "google-chrome"
# cask "iterm2"
# cask "jmeter"
# cask "notion"
# cask "owasp-zap"
# cask "postman"
# cask "sequel-ace"
# cask "slack"
# cask "skitch"
# cask "visual-studio-code"

mas 'BetterSnapTool', id: 417375580
