name: My Dotfiles CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Pull a dotfiles repository.
        uses: actions/checkout@v2
      - name: Setup dotfiles on Mac OS.
        run: sudo make init NAME="ryooou" EMAIL="test@example.com" && echo $DOTPATH
      - name: Fresh dotfiles.
        run: sudo make fresh
